name: CI/CD

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: main-ci-cd
  cancel-in-progress: false

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  deploy:
    needs: ci
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
